### ISSUE TITLE
docu concerning the plugin's configuration

### ISSUE THREAD

**Issue by utesche** [TIK-NFL/ilias-oc-plugin#39]
@all out there
 
Where the hell gets the world outside my office its information concerning configuring the plugin?
Nobody but me seems to have any problems with that. Damn!

- Do or do not the baseurls have to contain the portnumber?  The defaults (after first activation) suggests: not !?

- Are the base directories for 'Opencast Files' and 'XSendfile' located on the ILIAS- or the Opencast-Server? What are they good for, are they temp-folders for uploading?  Do they exists already or have I to create them?

- When trying to upload a file, I'm getting no visual response at all - only Firefox's network log states a 404 for 'http://192.168.1.11/ilias/51/Customizing/global/plugins/Services/Repository/RepositoryObject/Matterhorn/MHUpload/createEpisode' (which is a valid url on my ILIAS-server just up to 'MHUpload').  Same results for v0.2.2, v0.2.1 and v0.2.0.

Questions upon questions - how did YOU got them answered in ancient times?   :-/

wbr

**Comment by Legion2** [comment]
- the baseurls SHOULD NOT contain the portnumber, the default ports 80 and 443 are used.
- the 'base directories for Opencast Files' now 'Base directory for Opencast' exists on both the ilias and the opencast server and is an mounted network storage. It is the `org.opencastproject.storage.dir` directory of Opencast. 'XSendfile' now 'Distribution directory for ilias' is the directory where the opencast workflow publishes the episodes, so that directory MUST be accessible on the ilias server.
